repos:
  - repo: local
    hooks:
      - id: tests
        name: tests
        stages: [commit]
        language: system
        verbose: true
        entry: bash -c 'pytest'
        language: system
